name: Auto-Update Campsite Results

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-results:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run campsite search with browser headers
      run: python3 search_with_headers.py
      
    - name: Check if results changed
      id: check-changes
      run: |
        if git diff --quiet HEAD -- results.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes to results.json"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Results.json has been updated"
        fi
        
    - name: Commit and push changes
      if: steps.check-changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results.json
        git commit -m "Auto-update: Campsite search results - $(date -u +'%Y-%m-%d %H:%M UTC')"
        git push
